//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleBoilerTemp.Web.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_Particular_Unit
    {
        public int LinkId { get; set; }
        public Nullable<short> Item_id { get; set; }
        public Nullable<short> Unit_Id { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> VAT { get; set; }
    }
}
